### ISSUE TITLE
Cannot open multiple files in 'Colocalize'

### ISSUE THREAD

**Issue by Mahajan30** [GuckLab/impose#50]
I am able to open multiple files in 'Collect' and put masks/structures on them, but unable to open (same) multiple files in 'Colocalize'. The error I get is this:

Unhandled exception in Impose version 0.3.1:
Traceback (most recent call last):
  File "/Volumes/Impose_0.3.1/Impose.app/Contents/MacOS/impose/gui/colocalize.py", line 184, in on_add_data
    self.add_paths(paths)
  File "/Volumes/Impose_0.3.1/Impose.app/Contents/MacOS/impose/gui/colocalize.py", line 109, in add_paths
    self.session_scheme.append(pp)
  File "impose/session.py", line 157, in append
    structure_composite = self.scs.get_mean()
  File "impose/structure/composite_stack.py", line 80, in get_mean
    raise NotImplementedError("Averaging not implemented yet!")
NotImplementedError: Averaging not implemented yet!

Could you please look into this? Currently I have to close Impose after analysing each measurement. Resolving this would make life easy :)

**Comment by paulmueller** [comment]
The idea behind all of this is that if you load multiple structures, you can compute an average of that structure that you can than overlay with other data. Since this averaging feature (#4) is not implemented, you get a `NotImplementedError`.

What (I think) you would like to do does not align with the working principle of impose. You always can only analyze one dataset in one session. What could resolve your problem is to use "Clear Session" in the file menu. Then you don't have to restart impose anymore.

**Comment by Mahajan30** [comment]
Okay understood! Thanks!
